vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|12 Jul 2010 18:50:23 -0000
vti_extenderversion:SR|12.0.0.4518
vti_author:SR|JETPARTS\\kkoyamatsu
vti_modifiedby:SR|JETPARTS\\kkoyamatsu
vti_timecreated:TR|12 Jul 2010 18:50:23 -0000
vti_cacheddtm:TX|12 Jul 2010 18:50:23 -0000
vti_filesize:IR|20887
vti_cachedtitle:SR|Jet Parts Engineering: JPE News
vti_cachedbodystyle:SR|<body id="about_us" class="tertiary">
vti_cachedlinkinfo:VX|Q|css/screen.css S|./awmmenupath.gif S|./jpe_menu02.js H|email/NewPMA-Jul10.html H|http://water1st.org/index.html H|http://jetpartsengineering.com/philanthropy H|http://www.razoo.com/story/Jet-Parts-Engineering-Team-Water-Buffaloes H|email/NewPMA-May10.html H|http://www.aviationweek.com/events/current/mro/index.htm H|email/NewPMA-Mar10.html H|email/NewPMA-Dec09.html H|email/NewPMA-Nov09.html H|email/NewPMA-Sept09.html H|http://www.aviationweek.com/events/current/meu/index.htm H|http://www.acpc.com/ H|email/NewPMA-Jun09.html H|email/NewPMA-May09.html H|mailto:sales@jetpartsengineering.com H|http://www.jetpartsengineering.com/pdf/2009_Delta_Award.pdf H|http://www.aviationweek.com/conferences/mromain.htm H|ecom_prodSearch.aspx H|http://pmamarpa.com/website/board.html H|supps/seattle_02.pdf H|supps/alabama_38.pdf H|http://www.childhaven.org/new/index.php H|http://www.aerocontrols.com/ H|http://www.comair.com/ H|supps/alabama_37.pdf H|supps/alabama_36.pdf H|supps/alabama_34.pdf H|supps/alabama_35.pdf H|supps/alabama_33.pdf H|supps/alabama_27.pdf H|supps/alabama_28.pdf H|supps/alabama_29.pdf H|supps/alabama_30.pdf H|supps/alabama_31.pdf H|supps/alabama_32.pdf H|supps/alabama_26.pdf H|supps/alabama_25.pdf H|supps/alabama_22.pdf H|supps/alabama_23.pdf H|supps/alabama_24.pdf H|supps/alabama_20.pdf H|supps/alabama_19.pdf H|supps/alabama_20.pdf H|about_us-supplements.aspx S|images/1px.gif S|images/1px.gif S|images/1px.gif S|images/1px.gif S|images/1px.gif S|images/1px.gif S|images/1px.gif H|about_us-news_delta.aspx S|images/news-left.jpg S|images/1px.gif S|images/news-right.jpg
vti_cachedsvcrellinks:VX|NQUS|email/css/screen.css NSUS|email/awmmenupath.gif NSUS|email/jpe_menu02.js NHUS|email/email/NewPMA-Jul10.html NHHS|http://water1st.org/index.html NHHS|http://jetpartsengineering.com/philanthropy NHHS|http://www.razoo.com/story/Jet-Parts-Engineering-Team-Water-Buffaloes NHUS|email/email/NewPMA-May10.html NHHS|http://www.aviationweek.com/events/current/mro/index.htm NHUS|email/email/NewPMA-Mar10.html NHUS|email/email/NewPMA-Dec09.html NHUS|email/email/NewPMA-Nov09.html NHUS|email/email/NewPMA-Sept09.html NHHS|http://www.aviationweek.com/events/current/meu/index.htm NHHS|http://www.acpc.com/ NHUS|email/email/NewPMA-Jun09.html NHUS|email/email/NewPMA-May09.html NHUS|mailto:sales@jetpartsengineering.com NHHS|http://www.jetpartsengineering.com/pdf/2009_Delta_Award.pdf NHHS|http://www.aviationweek.com/conferences/mromain.htm NHUS|email/ecom_prodSearch.aspx NHHS|http://pmamarpa.com/website/board.html NHUS|email/supps/seattle_02.pdf NHUS|email/supps/alabama_38.pdf NHHS|http://www.childhaven.org/new/index.php NHHS|http://www.aerocontrols.com/ NHHS|http://www.comair.com/ NHUS|email/supps/alabama_37.pdf NHUS|email/supps/alabama_36.pdf NHUS|email/supps/alabama_34.pdf NHUS|email/supps/alabama_35.pdf NHUS|email/supps/alabama_33.pdf NHUS|email/supps/alabama_27.pdf NHUS|email/supps/alabama_28.pdf NHUS|email/supps/alabama_29.pdf NHUS|email/supps/alabama_30.pdf NHUS|email/supps/alabama_31.pdf NHUS|email/supps/alabama_32.pdf NHUS|email/supps/alabama_26.pdf NHUS|email/supps/alabama_25.pdf NHUS|email/supps/alabama_22.pdf NHUS|email/supps/alabama_23.pdf NHUS|email/supps/alabama_24.pdf NHUS|email/supps/alabama_20.pdf NHUS|email/supps/alabama_19.pdf NHUS|email/supps/alabama_20.pdf NHUS|email/about_us-supplements.aspx NSUS|email/images/1px.gif NSUS|email/images/1px.gif NSUS|email/images/1px.gif NSUS|email/images/1px.gif NSUS|email/images/1px.gif NSUS|email/images/1px.gif NSUS|email/images/1px.gif NHUS|email/about_us-news_delta.aspx NSUS|email/images/news-left.jpg NSUS|email/images/1px.gif NSUS|email/images/news-right.jpg
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=X-UA-Compatible IE=EmulateIE7 HTTP-EQUIV=Content-Language en-us HTTP-EQUIV=Content-Type text/html;\\ charset=utf-8 description data keywords data author Scott\\ Moffat,\\ et\\ al.
vti_charset:SR|utf-8
vti_language:SR|en-us
vti_title:SR|Jet Parts Engineering: JPE News
vti_backlinkinfo:VX|email/Default.aspx
