	<div id="footer">
		<p id="copyright">All Materials  1994 - 2007 Jet Parts Engineering, Inc.</p>
		<p id="footer_nav">
			<a href="index.asp">Home</a>&nbsp;|&nbsp;
			<a href="about_us.stm">About Us</a>&nbsp;|&nbsp;
			<a href="products.asp">Products</a>&nbsp;|&nbsp;
			<a href="support.stm">Support</a>&nbsp;|&nbsp;
			<a href="contact.stm">Contact</a>&nbsp;|&nbsp;
			<a href="support-why_register.stm#help">Help</a>
			<br />
			<a href="mailto:info@jetpartsengineering.com?subject=Webmaster Inquiry">Webmaster</a>&nbsp;|&nbsp;
			Web Design by <a href="http://mile13.com/" target="_new">Mile 13</a>
		</p>
	</div>
	<br/>
	<br/>