	<div id="header">
		<table>
			<tr>
				<td>
					<a href="default.aspx"><img id="logo" src="images/logo-JPE_000.gif" title="Jet Parts Engineering" width="201" height="57" /></a>
				</td>
				<td id="logon">
					
						<div id="input_fields" width="100%">
						</div>
<!--						
						<div width="100%" style="width: 400px; height: 34px">
							<a href=support_login.asp>Log-In</a>&nbsp;&nbsp;|&nbsp;&nbsp;
							<a href=support-register.asp>Register Me</a>&nbsp;&nbsp;|&nbsp;&nbsp;
							<a href="support-why_register.stm">Why register?</a>
						</div>
-->
					
				</td>
			</tr>
			<tr id="slogan_stripe">
				<td colspan="2" style="background-color: #000;" height="18px">
					<img src="images/header_slogan.gif" style="border: 0px; margin: 0px;"/>
				</td>
			</tr>
		</table>
	</div>