	<div id="footer">
		<p id="copyright">All Materials  1994 - 2010 Jet Parts Engineering, Inc.</p>
		<p id="footer_nav">
			<a href="default.aspx">Home</a>&nbsp;|&nbsp;
			<a href="about_us.aspx">About Us</a>&nbsp;|&nbsp;
			<a href="http://JPESmartBuyer.com/ecom_prodSearch.aspx" target="_New">Products</a>&nbsp;|&nbsp;
			<a href="ecom_Support.aspx">Support</a>&nbsp;|&nbsp;
			<a href="contact.aspx">Contact</a>
			<br />
			<a href="mailto:info@jetpartsengineering.com?subject=Webmaster Inquiry">Webmaster</a>
	
		</p>
	</div>
	<br/>
	<br/>