	<div id="header">
		<table>
			<tr>
				<td>
					<a href="index.asp"><img id="logo" src="http://www.jetpartsengineering.com/images/logo-JPE_000.gif" title="Jet Parts Engineering" width="201" height="57"/></a>
				</td>
				<td id="logon">
					<form>
						<div id="input_fields" width="100%">
						</div>

	
			<tr id="slogan_stripe">
				<td colspan="2" style="background-color: #000;" height="18px">
					<img src="http://www.jetpartsengineering.com/images/header_slogan.gif" style="border: 0px; margin: 0px;"/>
				</td>
			</tr>
		</table>
	</div>